"""Everything the page needs, in one request.

The person records are Markdown with a strict frontmatter block. The browser cannot
read those, and should not have to: this turns them into the plain script the page
loads, which is also what makes it one request instead of one per person — the
difference between working at 300 people and at 10,000.

Kept apart from the build script so the validator can rebuild the bundle in memory
and check the committed file still matches. That is what stops a stale bundle — and
therefore old data — reaching the site.
"""

from __future__ import annotations

import json

from .people import load_config, load_people, set_source_titles, to_browser_record
from .sources import load_sources


def _call(fn: str, value) -> str:
    # Compact separators and no ASCII escaping, because these records are full of é
    # and ë and the bundle is served as UTF-8.
    return f"FamilyTree.{fn}({json.dumps(value, ensure_ascii=False, separators=(',', ':'))});"


def build_bundle() -> str:
    sites, pages = load_sources()
    set_source_titles({s["id"]: s["title"] for s in [*sites, *pages]})
    config = load_config()
    roster, meta, site = config["roster"], config["meta"], config["site"]
    people = load_people(roster)

    registry = {s["id"]: s["title"] for s in [*sites, *pages]}

    def resolve(source_id):
        return registry.get(source_id, source_id)

    lines = [
        "// GENERATED by tools/build.py — do not edit.",
        "// Everything the page needs, in one request: the facts from data/ and the",
        "// wording from site/. Edit those and re-run the build.",
        "",
        _call("meta", {
            "root": config["root"],
            "roots": meta["roots"],
            "defaultSource": resolve(meta["defaultSource"]),
            "confidenceLabels": site["confidenceLabels"],
            "footer": site["footer"],
        }),
        # Branches cite the registry by id; the page wants something readable.
        _call("branches", {b: resolve(sid) for b, sid in config["branches"].items()}),
        _call("lineages", config["lineages"]),
        _call("groups", site["groups"]),
        _call("roster", roster),
        *[_call("person", to_browser_record(people[pid])) for pid in roster],
    ]
    return "\n".join(lines) + "\n"
